import logging
log = logging.getLogger(__name__)

from collections import Counter
import copy
import itertools
import uuid
import time

from collections import deque
import numpy as np
import threading


class QueueEmptyError(Exception):
    """Exception raised when attempting to pop from an empty queue."""
    pass


def as_iterator(x):
    """
    Ensure the input is treated as an iterator.

    If `x` is None, it defaults to 0. If `x` cannot be iterated over,
    it is returned as an infinitely cycling iterator yielding `x`.

    Parameters
    ----------
    x : any
        Value to convert to an iterator.

    Returns
    -------
    iterator
        Iterator yielding values.
    """
    if x is None:
        x = 0
    try:
        x = iter(x)
    except TypeError:
        x = itertools.cycle([x])
    return x


class NotifierQueue:
    """
    A thread-safe queue that triggers callbacks for specific events.

    Events currently supported include 'added', 'removed', 'decrement',
    and 'empty'. Callbacks are invoked on a background thread.
    """

    def __init__(self):
        self.queue = deque()
        self.worker_thread = threading.Thread(target=self.run, daemon=True)
        self.worker_thread.start()

        # Callbacks to trigger for the specified event.
        self._notifiers = {
            'added': [],
            'removed': [],
            'decrement': [],
            'empty': [],
        }

    def connect(self, callback, event='added'):
        """
        Connect a callback to the specified event.

        Parameters
        ----------
        callback : callable
            Function to call when event occurs.
        event : str, optional
            Event to connect to, by default 'added'.
        """
        if event not in self._notifiers:
            raise KeyError(f'Event "{event}" not valid')
        self._notifiers[event].append(callback)

    def notify(self, event, info):
        """
        Notify all connected callbacks of an event.

        Parameters
        ----------
        event : str
            Event name.
        info : dict
            Information dictionary passed to the callbacks.
        """
        self.queue.append((event, info))

    def run(self):
        """Worker thread loop to dispatch events."""
        while True:
            while self.queue:
                event, info = self.queue.popleft()
                for cb in self._notifiers[event]:
                    cb(info)
            time.sleep(0.001)

    def join(self):
        self.queue.join()


class AbstractSignalQueue:
    """
    Base class for a signal queue.

    Manages the queuing, tracking, and generation of waveforms for output.

    Parameters
    ----------
    fs : float, optional
        Sampling rate of output that will be using this queue.
    """

    def __init__(self, fs=None):
        self.notifier = NotifierQueue()

        # Used internally to track intertrial silent period.
        self._delay_samples = 0

        # Dictionary of generators or arrays. Each token added to the queue has
        # a unique ID. The token is associated with either a class-based
        # generator (which can be restarted to generate a new waveform) or an
        # already-generated waveform.
        self._data = {}

        # Tracks order of items added to queue. Subclasses will incorporate
        # this into their algorithms to determine the actual ordering of the
        # stimuli (e.g., first-in, first-out, interleaved, etc.).
        self._ordering = []

        # Current waveform generator for trials.
        self._source = None

        # Total samples generated by queue
        self._samples = 0

        # Is stimulus generation paused?
        self._paused = False

        # Is queue complete?
        self._empty = False

        # Sampling rate needed to generate waveforms at. This is required since
        # it's used in some calculations of timing.
        self._fs = fs

        # Start time of queue relative to acquisition start.
        self._t0 = 0

        # Tracks waveforms generated by queue. This is used in the event we
        # need to pause stimulus generation.
        self._generated = []

    def clone(self):
        return copy.deepcopy(self)

    @property
    def fs(self):
        return self._fs

    def get_ts(self):
        return self._samples / self._fs

    def remaining_trials(self, key):
        return self._data[key]['trials']

    def rewind_samples(self, t, check=True):
        """
        Rewind the queue back to a specific time.

        Parameters
        ----------
        t : float
            Time in seconds to rewind samples back to.
        check : bool, optional
            If True, new time must be before current time of queue. If False,
            can be set to a later time. By default True.
        """
        # Reset the samples
        new_sample = int(round((t - self._t0) * self._fs))
        if check and (new_sample > self._samples):
            raise ValueError(f'Cannot rewind past last sample generated. ' \
                             f'Requested {t:.3f}s, last sample was {self.get_ts():.3f}s.')
        self._samples = new_sample

    def pause(self, t=None):
        self._paused = True
        if t is not None:
            self.cancel(t)
            self.requeue(t)
            self.rewind_samples(t)

    def cancel(self, t, delay=0):
        for info in self._generated[::-1]:
            if (info['t0'] + info['duration']) > t:
                self.notifier.notify('removed', info)

        if self._source is not None:
            info = self._generated[-1]
            if info['decrement']:
                self._data[info['key']]['trials'] += 1
            self._source = None

        self._delay_samples = int(round(delay * self._fs))

    def requeue(self, t):
        """
        Requeues all trials scheduled after `t0`.

        Note that this only requeues trials for which the trial counter was
        automatically decremented when the waveform was generated by the queue.
        When using artifact reject, trial counters are sometimes decremented by
        the artifact reject algorithm instead (e.g., ABRs) and the assumption
        is that the external algorithm will not receive "canceled" trials and,
        therefore, will not decrement the counter.

        Parameters
        ----------
        t : float
            Time in seconds after which to requeue trials.
        """
        to_requeue = []
        for info in self._generated[::-1]:
            if (info['t0'] + info['duration']) <= t:
                continue
            if info['decrement']:
                to_requeue.append(info['key'])

        # to_requeue is from last to first in time. Therefore, if we
        # encounter a key that isn't present in _ordering, we should insert
        # it at the beginning of the list.
        for key in to_requeue:
            if key not in self._ordering:
                self._ordering.insert(0, key)

        trials = {k: self._data[k]['trials'] for k in self._data.keys()}
        for key, count in Counter(to_requeue).items():
            self._data[key]['trials'] += count
        trials = {k: self._data[k]['trials'] for k in self._data.keys()}

    def resume(self, t=None):
        """
        Resumes generating trials from queue

        Parameters
        ----------
        t : float
            Time, in sec, to resume generating trials from queue.
        """
        if t is not None:
            self.rewind_samples(t, False)
        self._paused = False

    def is_empty(self):
        return self._empty

    def set_fs(self, fs):
        # Sampling rate at which samples will be generated.
        self._fs = fs

    def set_t0(self, t0):
        # Sample at which queue was started relative to experiment acquisition
        # start.
        self._t0 = t0

    def _add_source(self, source, trials, delays, duration, metadata):
        key = str(uuid.uuid4())
        if duration is None:
            if isinstance(source, np.ndarray):
                duration = source.shape[-1]/self._fs
            else:
                duration = source.get_duration()

        data = {
            'source': copy.deepcopy(source),
            'trials': trials,
            'requested_trials': trials,
            'delays': as_iterator(delays),
            'duration': duration,
            'metadata': metadata,
        }
        self._data[key] = data
        return key

    def get_max_duration(self):
        def get_duration(source):
            try:
                return source.get_duration()
            except AttributeError:
                return source.shape[-1]/self._fs
        return max(get_duration(d['source']) for d in self._data.values())

    def connect(self, callback, event='added'):
        self.notifier.connect(callback, event)

    def insert(self, source, trials, delays=None, duration=None, metadata=None):
        k = self._add_source(source, trials, delays, duration, metadata)
        self._ordering.insert(k)
        return k

    def append(self, source, trials, delays=None, duration=None, metadata=None):
        k = self._add_source(source, trials, delays, duration, metadata)
        self._ordering.append(k)
        return k

    def extend(self, sources, trials, delays=None, duration=None,
               metadata=None):

        base_err = '{param} must be a scalar or a sequence of length {n}'
        n = len(sources)

        if np.iterable(trials):
            if len(trials) != n:
                raise ValueError(base_err.format('trials', n))
        else:
            trials = itertools.cycle([trials])

        if np.iterable(delays):
            if len(delays) != n:
                raise ValueError(base_err.format('delays', n))
        else:
            delays = itertools.cycle([delays])

        if np.iterable(duration):
            if len(duration) != n:
                raise ValueError(base_err.format('duration', n))
        else:
            duration = itertools.cycle([duration])

        if np.iterable(metadata):
            if len(metadata) != n:
                raise ValueError(base_err.format('metadata', n))
        else:
            metadata = itertools.cycle([metadata])

        uuids = []
        for args in zip(sources, trials, delays, duration, metadata):
            uuids.append(self.append(*args))
        return uuids

    def count_factories(self):
        return len(self._ordering)

    def count_trials(self):
        """
        Count remaining trials.

        Returns
        -------
        int
            Number of remaining trials.
        """
        return int(sum(max(v['trials'], 0) for v in self._data.values()))

    def count_requested_trials(self):
        """
        Count total requested trials.

        Returns
        -------
        int
            Total number of requested trials across all keys.
        """
        return int(sum(v['requested_trials'] for v in self._data.values()))

    def next_key(self):
        raise NotImplementedError

    def pop_next(self, decrement=True):
        key = self.next_key()
        return key, self.pop_key(key, decrement=decrement)

    def pop_key(self, key, decrement=True):
        """
        Remove one trial of the specified key from queue and return data.

        Parameters
        ----------
        key : str
            UUID of the stimuli source to pop.
        decrement : bool, optional
            If True, decrements the remaining trials. By default True.

        Returns
        -------
        dict
            Information regarding the trial (source, delays, duration, etc).
        """
        data = self._data[key]
        if decrement:
            self.decrement_key(key)
        return data

    def remove_key(self, key):
        """
        Removes key from queue entirely, regardless of number of trials.

        Parameters
        ----------
        key : str
            UUID of the stimuli source.
        """
        self._ordering.remove(key)

    def decrement_key(self, key, n=1):
        """
        Decrement trials for key

        Parameters
        ----------
        key : UUID
            Key to decrement
        n : int
            Number of trials to decrement by

        Returns
        -------
        complete : bool
            True if no trials left for key, False otherwise.
        """
        if key not in self._ordering:
            raise KeyError('{} not in queue'.format(key))
        self._data[key]['trials'] -= n
        if self._data[key]['trials'] <= 0:
            self.remove_key(key)
            return True
        self.notifier.notify('decrement', {'key': key})
        return False

    def _get_samples_waveform(self, samples):
        if samples > len(self._source):
            waveform = self._source
            self._source = None
        else:
            waveform = self._source[:samples]
            self._source = self._source[samples:]
        return waveform

    def _get_samples_generator(self, samples):
        samples = min(self._source.n_samples_remaining(), samples)
        waveform = self._source.next(samples)
        if self._source.is_complete():
            self._source = None
        return waveform

    def next_trial(self, decrement=True):
        """
        Set up the next trial.

        This has immediate effect. If you call this (from external code), the
        current trial will not finish.

        Parameters
        ----------
        decrement : bool, optional
            If True, decrement trial counters, by default True.
        """
        key, data = self.pop_next(decrement=decrement)

        # Source can either be a generator or an array. If generator, be sure to reset.
        self._source = data['source']
        try:
            self._source.reset()
            self._get_samples = self._get_samples_generator
        except AttributeError:
            self._source = data['source']
            self._get_samples = self._get_samples_waveform

        # Now, determine the next ITI (as specified by the delay generator)
        delay = next(data['delays'])
        self._delay_samples = int(round(delay*self._fs))
        if self._delay_samples < 0:
            raise ValueError(f'Invalid value for ITI interval. Got {delay}.')

        t0 = self._t0 + (self._samples/self._fs)
        info = {
            't0': t0,                       # Time re. acq. start
            'duration': data['duration'],   # Duration of token
            'key': key,                     # Unique ID
            'metadata': data['metadata'],   # Metadata re. token
            'decrement': decrement,         # Automatically decr. trial ctr.?
        }
        self._generated.append(info)
        self.notifier.notify('added', info)

    def pop_buffer(self, samples, decrement=True):
        """
        Return the requested number of samples.

        Removes stack of waveforms in order determined by internal mechanism,
        but only returns the requested number of samples. If a partial fragment
        of a waveform is returned, the remaining part will be returned on
        subsequent calls to this function.

        Parameters
        ----------
        samples : int
            Number of samples to return.
        decrement : bool, optional
            If True, decrement the counters as waveforms start, by default True.

        Returns
        -------
        ndarray
            1D array containing the requested samples.
        """
        o = 0
        waveform = np.empty(samples)
        while samples > 0:
            try:
                w = self._pop_buffer(samples, decrement)
                s = w.shape[-1]
                waveform[o:o+s] = w
                o += s
                samples -= s
                self._samples += s
            except QueueEmptyError:
                waveform[o:] = 0
                self._samples += samples
                self._empty = True
                self.notifier.notify('empty', {})
                samples = 0
        return waveform

    def _pop_buffer(self, samples, decrement):
        '''
        Encodes logic for deciding what segment needs to be generated. It must
        return *up to* the number of samples requested, but can be less if
        needed.
        '''
        # If paused, return a stream of zeros.
        if self._paused:
            return np.zeros(samples)

        # Load samples from current source
        if self._source is not None:
            return self._get_samples(samples)

        # Insert intertrial interval delay if one exists
        if self._delay_samples > 0:
            n = min(self._delay_samples, samples)
            self._delay_samples -= n
            return np.zeros(n)

        # Set up next trial
        if self._source is None:
            self.next_trial(decrement)
            return np.empty(0)

    def get_closest_key(self, t):
        for info in self._generated[::-1]:
            if info['t0'] <= t:
                return info['key']
        return None

    def get_info(self, key):
        return self._data[key].copy()


class FIFOSignalQueue(AbstractSignalQueue):
    """
    Return waveforms based on the order they were added to the queue.
    """

    def next_key(self):
        if len(self._ordering) == 0:
            raise QueueEmptyError
        return self._ordering[0]


class InterleavedFIFOSignalQueue(AbstractSignalQueue):
    """
    Return waveforms based on the order they were added to the queue.
    However, trials are interleaved.

    Parameters
    ----------
    keep_complete_waveforms : bool, optional
        If True, include all waveforms in the sequence even if we have acquired
        the desired number for a given waveform. This ensures that the timing
        between waveforms is not altered. If False, only includes waveforms
        that we have not achieved the desired number of trials for.
        By default True.
    """

    def __init__(self, keep_complete_waveforms=True, **kwargs):
        super().__init__(**kwargs)
        self._i = -1
        self._complete = False
        self._keep_complete_waveforms = keep_complete_waveforms

    def next_key(self):
        if self._complete:
            raise QueueEmptyError
        while True:
            self._i = (self._i + 1) % len(self._ordering)
            key = self._ordering[self._i]
            if self._keep_complete_waveforms:
                break
            elif self._data[key]['trials'] > 0:
                break
        return key

    def decrement_key(self, key, n=1):
        if key not in self._ordering:
            raise KeyError('{} not in queue'.format(key))
        self._data[key]['trials'] -= n

        for key, data in self._data.items():
            if data['trials'] > 0:
                return False

        self._complete = True
        return True

    def count_trials(self):
        return sum(max(v['trials'], 0) for v in self._data.values())


class RandomSignalQueue(AbstractSignalQueue):
    """
    Return waveforms in random order.
    """

    def next_key(self):
        if len(self._ordering) == 0:
            raise QueueEmptyError
        i = np.random.randint(0, len(self._ordering))
        return self._ordering[i]


class BlockedRandomSignalQueue(InterleavedFIFOSignalQueue):

    def __init__(self, seed=0, **kwargs):
        super().__init__(**kwargs)
        self._i = []
        self._rng = np.random.RandomState(seed)

    def next_key(self):
        if self._complete:
            raise QueueEmptyError
        if not self._i:
            # The blocked order is empty. Create a new set of random indices.
            i = np.arange(len(self._ordering))
            self._rng.shuffle(i)
            self._i = i.tolist()
        i = self._i.pop()
        return self._ordering[i]


class GroupedFIFOSignalQueue(FIFOSignalQueue):
    """
    Iterates through each waveform in the order it was added, but in blocks.

    If the block size is 4 and there are 8 waveforms queued (A B C D E F G H):
    The queue iterates through A B C D until all trials have been presented,
    then it shifts to E F G H.

    Parameters
    ----------
    group_size : int
        Number of items to group together.
    """

    def __init__(self, group_size, **kwargs):
        super().__init__(**kwargs)
        self._group_size = group_size
        self._i = -1

    def next_key(self):
        if len(self._ordering) == 0:
            raise QueueEmptyError
        self._i = (self._i + 1) % self._group_size
        return self._ordering[self._i]

    def decrement_key(self, key, n=1):
        if key not in self._ordering:
            raise KeyError('{} not in queue'.format(key))
        self._data[key]['trials'] -= n

        # Check to see if the group is complete. Return from method if not
        # complete.
        for key in self._ordering[:self._group_size]:
            if self._data[key]['trials'] > 0:
                return False

        # If complete, remove the keys
        for key in self._ordering[:self._group_size]:
            self.remove_key(key)

        return True


class BlockedFIFOSignalQueue(GroupedFIFOSignalQueue):
    """
    Iterates through each waveform in a block equal to the number of queued stimuli.

    Like the `GroupedFIFOSignalQueue` except block size is automatically set to
    the number of waveforms queued. If you have 8 waveforms queued (A-H),
    the queue iterates through A B C D E F G H until all trials have been
    presented.
    """
    def __init__(self, **kwargs):
        super().__init__(group_size=0, **kwargs)

    def append(self, *args, **kwargs):
        self._group_size += 1
        return super().append(*args, **kwargs)


queues = {
    'first-in, first-out': FIFOSignalQueue,
    'interleaved first-in, first-out': InterleavedFIFOSignalQueue,
    'blocked first-in, first-out': BlockedFIFOSignalQueue,
    'grouped first-in, first-out': GroupedFIFOSignalQueue,
    'random': RandomSignalQueue,
    'blocked random': BlockedRandomSignalQueue,
}
